<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
        ], function ($) {
        var modal = $('#prompt-modal-content').modal({
            autoOpen: true,
            responsive: true,
            clickableOverlay: false,
            modalClass: 'modal-custom',
            title: 'Popup',
            buttons: [{
                text: $.mage.__('Take me back to the homepage'),
                class: 'action close-popup wide',
                click: function () {
                    window.location.href = '/';
                }
            }]
        });
        modal.on('modalclosed', function () {

        });
        $("#login-nav").on('click',function(){
            $("#prompt-modal-content").modal("openModal");
        });
    });
</script>