<div class="dashboard-container row">
    <div class="dashboard-main col-m-8 col-m-push-4">
        <!--Department Name/Content !-->
        <script>
            require(["jquery","mage/backend/tabs"], function($){
                $(function() {
                    $('#tab_element').tabs({
                        active: 'tab1_content',  // active tab elemtn id
                        destination: '#tab_element_content', // tab content destination element id
                        shadowTabs: []
                    });
                });
            });
        </script>
        <div id="tab_element">
            <ul class="tabs-horiz" >
                <li>
                    <a href="#tab1_content">
                <span>
                    <?php echo __("Create new"); ?>
                </span>
                    </a>
                </li>
            </ul>
        </div>
        <div id="tab_element_content">

