
    <div class="dashboard-secondary col-m-4 col-m-pull-8">
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?= $block->escapeHtml(__('Topic List')) ?></div>
            <a href="#" id="quyet" >Quyet</a>
            <input id="var" type="hidden" />
            <div id="tam">
            </div>
        </div>
    </div>
</div>
    <script type="text/javascript">
        require([
            'jquery',
            'FormData',
            'Magento_Ui/js/modal/alert'
        ], function ($) {
            $(document).ready(function() {
                $("#var").val('<?= $block->getUrl('helptick/topic/topiclist') ?>');
                var url = '<?= $block->getUrl('helptick/topic/topiclist') ?>';
                $.ajax({
                    url: "<?= $block->getUrl('helptick/topic/topiclist') ?>",
                    dataType :"JSON",
                    success : function(data)
                    {
                        console.log(data.content);
                    }
                });
                $("#quyet").on('click',function(){
                    $.post("<?= $block->getUrl('helptick/topic/topiclist') ?>",
                        {
                            name: "Donald Duck",
                            city: "Duckburg"
                        },
                        function(data, status){
                            console.log(data);
                        });
                });
                    //$.ajax({
                    //    type: "POST",
                    //    url: "<?//= $block->getUrl('helptick/topic/topiclist') ?>//",
                    //    contentType: "application/json",
                    //    dataType: "json",
                    //    success: function(response) {
                    //        console.log(response);
                    //    },
                    //    error: function(response) {
                    //        console.log(response);
                    //    }
                    //})
        });
});
    </script>
